### ISSUE TITLE
Mismatch of roles after update

### ISSUE THREAD

**Issue by tmberthold** [sovity/authority-portal#104]
### Description - What happened? *

We observed a inconsistency when the admin changes a users role. The role-definitions do not get updated in all relevant areas at the same time (see screenshot). I can understand, that it may be needed to log in again to finalize the change of a a users role. However on this I would prefer the process of the last version, where a user got automatically logged out when his role was changed as this did not lead to inconsistencies.

### Expected Behavior *

/

### Observed Behavior *

/

**Comment by kamilczaja** [comment]
Duplicate of #111
