### ISSUE TITLE
Different Styles on Login/Log out Pages

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#113]
### Description - What happened? *

The styles on the onboarding pages differ and it would be good if we could harmonise a few inconsistencies. I've attached some screenshots.

Could you have a look at the following points and standardise them:

Font: The Font in Screen 1 is Arial, in Screen 2 Open Sans is used. Please use Arial.
Position: Screen 1 is in the center of the window, whereas Screen2 is moved upwards.
Button Design: Screen 1 uses rectangular Buttons in black and white, the button on Screen 2 is yellow and rather round.
Logo: the MDS Logo differs (the Logo in Screen 2 being the prefered option).
Background: Screen 1 has no colorful background, in Screen 2 a grey box is used in the backgound.
I think the logout page uses the same styling as screen 2 and would therefore also need to be adapted.

Please reach out anytime, if anything is unclear or additional information is need.

### Expected Behavior *

/

### Observed Behavior *

/

### Screenshots

Screen 1
![Screen1](https://github.com/sovity/authority-portal/assets/36418748/6269201c-424d-4a7a-b70a-1b9c1c3be010)
Screen 2
![Screen2](https://github.com/sovity/authority-portal/assets/36418748/c89127d4-38b8-4222-b33f-4a46b46df8d1)
Logout Screen
<img width="958" alt="Logout_Screen" src="https://github.com/sovity/authority-portal/assets/36418748/0dc4990d-a7b6-40f2-9eec-f118316425ea">

**Comment by illfixit** [comment]
@jkbquabeck second and third screenshots are Keycloak. Changing and testing the keycloak theme is much more difficult than the html in the first screenshot but the html version looks much better

**Comment by kamilczaja** [comment]
The Keycloak pages are really troublesome, especially since the Keycloak themes use some cursed HTML knock-off. While this would take time and is out-of-scope for a simple bugfix, me might consider ditching the Keycloak login pages and crafting a custom solution to authenticate against Keycloak using e.g. direct grants for the client configuration.

**Comment by jkbquabeck** [comment]
Priority: font and logo;
