### ISSUE TITLE
Connector endpoint protocol validation mismatch between FE/BE

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#115]
### Description - What happened? *

In the connector registration, the URL input validation is mismatched in the FE. The backend checks for the `https` protocol, the FE only vor a valid URL.

### Expected Behavior *

Input field validation should fail on `http`

### Observed Behavior *

The user can reach the end of the registration form only to see an error message sent from BE

### Screenshots

1
<img width="692" alt="1" src="https://github.com/sovity/authority-portal/assets/36418748/b908ecba-26f2-4df1-8a64-9bd1e41b1db9">
2
<img width="762" alt="2" src="https://github.com/sovity/authority-portal/assets/36418748/b8005aea-6786-49b8-947d-691fefbc1fe5">
3
<img width="353" alt="3" src="https://github.com/sovity/authority-portal/assets/36418748/fe762048-510d-471c-b6a6-c2fffcff91fb">
4
<img width="458" alt="4" src="https://github.com/sovity/authority-portal/assets/36418748/8c2421d6-4c95-4b71-8e4d-48b9acfbfd79">
5
<img width="474" alt="5" src="https://github.com/sovity/authority-portal/assets/36418748/e410b840-d103-4ae9-820f-ecacf5768571">

**Comment by kamilczaja** [comment]
@jridderbusch Any update on what this is about?

**Comment by kamilczaja** [comment]
After a quick discussion with @sybereal we should check for both `http` and `https`, since both protocols are valid to talk to connectors.
