### ISSUE TITLE
Users can't delete themselves

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#127]
### Description - What happened? *

Users should be able to delete themselves, therefore we need to add a "Delete" button (with the same confirmation behavior, as when trying to delete another user) to the own profile page.

### Expected Behavior *

?

### Observed Behavior *

?

**Comment by jridderbusch** [comment]
@illfixit The BE part for this is done in the linked PR

**Comment by illfixit** [comment]
@jridderbusch but in case it's the last admin and other edge cases he/she still can't do it, right?

**Comment by jridderbusch** [comment]
@illfixit The behavior should be exactly the same, as deleting another user
