### ISSUE TITLE
Form validators need to be fixed

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#161]
### Description - What happened? *

With version 2.1.2 we observed a new bug, that has to do with required input fileds. Sometimes the user is asked to input information eventhough the info is already entered. This occures when data is inserted by copy and paste. The Registration Process as well as the profil pages are affected by this. I attached one screenshot from the registration process where the input is not recognized due to a trailing space. The scond screenshot shows part of the organizations profile. I removed trailing spaces but unfortunatelly can't pinpoint why the input is not recognized.

### Expected Behavior *

?

### Observed Behavior *

?

### Screenshots

1.
<img width="642" alt="required_field_input_user_registration" src="https://github.com/sovity/authority-portal/assets/36418748/87232515-3e46-4f0c-8f1e-77930bb7f5f7">

2.
<img width="725" alt="required_field_input_organization_menu" src="https://github.com/sovity/authority-portal/assets/36418748/b8d64bb3-03b9-45c8-b771-568660a77338">

**Comment by illfixit** [comment]
I can imagine it happening but I can't reproduce the bug hmm
it works even with validations in chrome and firefox windows 10

![Image](https://github.com/sovity/authority-portal/assets/66363651/0ba12bde-64bf-4220-bc41-2abc928039eb)
![Image](https://github.com/sovity/authority-portal/assets/66363651/36a0b959-00c3-4fdc-a985-f1a6299995f0)

**Comment by illfixit** [comment]
> I reproduced the issue with the phone number. A trailing space indeed causes the validation to fail. My guess is that the regular expression does not expect a space at the end (or beginning for that matter) of the string. Simplest solution to that would be to strip trailing whitespaces for the validation (and for the subsequent API request).
> 
> As for the description, I could not reproduce that behavior. Looking at the provided screenshot, I noticed that there is no validation error under the input field which suggests to me that the validation does not fail. The field border being red is most probably caused by another issue which causes all input fields on the second registration page to be red until touched. I'm sure that clicking away from that field will make it appear normal again since the validation was successful.

striping trailing whitespace in real time is a bad idea because it'll damage user experience if user don't copy paste but type the number. 

The easy solution would be just to fix the phone number validator to allow whitespaces at the end
