### ISSUE TITLE
Logo cutoff

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#165]
### Description - What happened? *

It seems like that with the adaption of the UI the Logo on the OTP-configuration page is not displayed fully. I can not verify that the bug is solved, since the logo is cut off on that page. I have attached a screenshot. It is not possible to scroll up further.

### Expected Behavior *

?

### Observed Behavior *

?

### Screenshots

<img width="675" alt="Logo_cutoff" src="https://github.com/sovity/authority-portal/assets/36418748/29deb014-ee43-425d-9047-1c782abfa931">

**Comment by illfixit** [comment]
yes, just checked it, it's cropped when the browser is vertically not fully opened
