### ISSUE TITLE
Add connector - Generated certificate text field greyed out

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#19]
### Description - What happened? *

After generating the certificate in the Certificate field the generated certificate text is shown as greyed-out colour.
Also, Generate & Download Certificate (Slow) is mentioned. Should this mention of "slow" still be present there?

### Expected Behavior *

Should show in dark black color once the certificate is generated.

### Observed Behavior *

Generate Certificate after generating the certificate in the Certificate field the generated certificate text is shown as greyed out colour.

### Steps to Reproduce

1. Launch app with valid credentials
2. Click on Connectors
3. Click on Add Connectors
4. Enter all valid data
5. Click on Next
6. Enter all valid data
7. Click on Generate Certificate

### Screenshots

![Screenshot-2024-03-10-at-13 12 38](https://github.com/sovity/authority-portal/assets/36418748/b2d7ddd6-27b9-4bae-a4bc-1af90412ca07)

**Comment by kamilczaja** [comment]
In my opinion, it works as designed. Since the certificate field is not meant to be interacted with, it only makes sense to grey it out to convey that message to the user.

Only thing I would change is the wording. "Slow" is vague and should be replaced with a label below the button along the lines of "Generating a new certificate can take some time"

**Comment by illfixit** [comment]
@jkbquabeck what do you think?

**Comment by jkbquabeck** [comment]
@illfixit I fully agree with @kamilczaja

**Comment by illfixit** [comment]
@kamilczaja @jkbquabeck does it look good enough?

![Image](https://github.com/sovity/authority-portal/assets/66363651/5a9ff1a6-5f1a-4b0d-a902-89ec5848c619)

**Comment by kamilczaja** [comment]
> @kamilczaja @jkbquabeck does it look good enough?
> 
> ![Image](https://private-user-images.githubusercontent.com/66363651/311770909-5a9ff1a6-5f1a-4b0d-a902-89ec5848c619.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNzI4MzMsIm5iZiI6MTcxMDE3MjUzMywicGF0aCI6Ii82NjM2MzY1MS8zMTE3NzA5MDktNWE5ZmYxYTYtNWYxYS00YjBkLWE5MDItODllYzU4NDhjNjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE1NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZjc5MmY0YzMyZjc5YmEyOWNmOTVkYTA2YTg3YjhjZWFjOTgwZDg1OWE5OTAzNzM1ODY0MTVjNTQ5ZGMzYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xy7LKj1gdqdhHxwmO97hLiJFs-DTrryTTH_I28NbZ7w)

I would remove the asterisk, I think the proximity is enough to get the point

**Comment by illfixit** [comment]
> > @kamilczaja @jkbquabeck does it look good enough?
> > ![Image](https://private-user-images.githubusercontent.com/66363651/311770909-5a9ff1a6-5f1a-4b0d-a902-89ec5848c619.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNzI4MzMsIm5iZiI6MTcxMDE3MjUzMywicGF0aCI6Ii82NjM2MzY1MS8zMTE3NzA5MDktNWE5ZmYxYTYtNWYxYS00YjBkLWE5MDItODllYzU4NDhjNjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE1NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZjc5MmY0YzMyZjc5YmEyOWNmOTVkYTA2YTg3YjhjZWFjOTgwZDg1OWE5OTAzNzM1ODY0MTVjNTQ5ZGMzYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xy7LKj1gdqdhHxwmO97hLiJFs-DTrryTTH_I28NbZ7w)
> 
> I would remove the asterisk, I think the proximity is enough to get the point

Jakob said the same, done :)
