### ISSUE TITLE
Restrict user invitation based on company domain of mail address

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/authority-portal#212]
Adopt similar mechanisms like those of MIRO and other SaaS solutions.
![image](https://github.com/sovity/authority-portal/assets/22075788/4f771ef9-57e8-4743-a380-ad651a7e3031)

**Comment by kamilczaja** [comment]
@SebastianOpriel please elaborate on this

**Comment by kamilczaja** [comment]
**2024-06-03**
Restrict e-mail domain to prevent organization admins to invite people from other companies.
Maybe implement a mechanism to join existing organizations (verified by email domain)

**Comment by ip312** [comment]
Hi @kamilczaja. In the MDS we have a situation in which admins need to invite people from other companies, e.g. _admin@carmanufacturer.com_ needs to invite _developer@softwareprovider.com._
