### ISSUE TITLE
Register organization: Misplacement of "Other" Option in Industry Field Dropdown List

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#22]
### Description - What happened? *

In the Authority Portal, within the Register Organization Page - Org Profile section, the dropdown list for the Industry field is not adhering to the expected order. Specifically, the "Other" option is not positioned at the end of the list, as is customary for such selections. This deviation from standard UI practices can lead to user confusion and a less intuitive experience.

### Expected Behavior *

The "Other" option should be displayed as the last item in the dropdown list for the Industry field, following the conventional design practices to enhance user navigation and clarity.

### Observed Behavior *

The "Other" option is not placed at the end of the dropdown list options, contrary to common user interface guidelines and the expected design.

### Steps to Reproduce

1. Navigate to the Authority Portal's Register Organization Page
2. Proceed to the Org Profile page
3. Click on the dropdown list for the Industry field
4. Observe the position of the "Other" option within the dropdown list

### Screenshots

![Screenshot-2024-03-10-at-13 31 34](https://github.com/sovity/authority-portal/assets/36418748/4aaba7c6-4653-4ad7-b6ea-638273b9f85e)

**Comment by illfixit** [comment]
it's just aphabetically sorted, will fix it fast :)
