### ISSUE TITLE
Register organisation: Inconsistent Pagination Number Color

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#23]
### Description - What happened? *

In the "Register Organization - User Details Page" of the Authority Portal, an inconsistency in the color scheme of pagination numbers has been identified. Specifically, within the Email Verification section, the pagination number text for page 3 displays in black, whereas the pagination numbers for pages 1 and 2 are in white. For visual consistency and improved user experience, all pagination numbers should have the same color.

### Expected Behavior *

All pagination numbers in the Email Verification section should display in the same color to ensure visual consistency and coherence across the user interface.

### Observed Behavior *

The pagination number for page 3 is displayed in black, contrasting with the white color of pagination numbers for pages 1 and 2, leading to visual inconsistency.

### Steps to Reproduce

1. Navigate to the "Register Organization - User Details Page" on the Authority Portal.
2. Proceed to the Email Verification section.
3. Observe the pagination numbers at the top of the section.
4. Note that the color of the number for page 3 is black, while the numbers for pages 1 and 2 are displayed in white.

### Screenshots

![Screenshot-2024-03-10-at-13 28 29](https://github.com/sovity/authority-portal/assets/36418748/728e107e-d74d-4bd5-a771-335bddd2effa)

**Comment by illfixit** [comment]
@jkbquabeck white means in this situation that this step is allowed, black the opposite. Should we still change it into white?

**Comment by illfixit** [comment]
ok. this issue is closed then :)
