### ISSUE TITLE
Fix `Organizations` UI cut-off

### ISSUE THREAD

**Issue by tmberthold** [sovity/authority-portal#246]
**Describe the bug**
The table displaying all organizations is slightly cut off.

**Steps To Reproduce**
1. Log in as Authority User or Authority Admin.
2. Navigate to "Organizations" in the Authority Section.
3. The table displaying all organizations is slightly cut off, even when your zooming out.

**Expected behavior**
The table should be fully visible.

**Screenshots**
![image](https://github.com/user-attachments/assets/7376cf49-4b18-4703-b0b9-91557c63a222)

**MDS Versions (please complete the following information):**
 - Portal: 2.3.0

**Comment by kamilczaja** [comment]
Cannot reproduce in 3.1.0

Maybe you can find something during functional tests @AbdullahMuk @jkbquabeck 
Otherwise there is not enough information to find the root of this issue or the issue is already fixed accidentally seeing that this refers to version 2.3.0

**Comment by illfixit** [comment]
Here's what the latest version looks like


![Image](https://github.com/user-attachments/assets/0bfe2e45-42ac-429f-82f0-4400bec95fc2)

**Comment by AbdullahMuk** [comment]
Following dev team analysis, we will not fix this bug because 

- bug has little-to-no impact on the operation of the system even though it is an annoyance in the UI / UX.
- bug happens only during zoom out. 
- bug is not present in latest version of AP which will rollout soon to users.
