### ISSUE TITLE
Organizations-page not updated when switching between environments

### ISSUE THREAD

**Issue by tmberthold** [sovity/authority-portal#255]
### Description - What happened? *

The content of the "Organizations" page isn't updated when switching between environments.

### Expected Behavior *

This is a bug, as the expected behaviour would be: all the values will be updated immediately after switching the environment.

### Observed Behavior *

The content of the "Organizations" page isn't updated when switching between environments.

### Steps to Reproduce

Steps for reproduction:
- In Portal, in Test environment, open the "Organizations" page
- Switching to the other environment: the values at "No. of Connectors" and "No. of Data Offers" are not changed accordingly.

### Context Information

The workaround would be: after switching the environment, I click on another menu item (for example "All Connectors") and then come back to this "Organizations" page. The mentioned values are then updated.

If I click on the refresh button of the web browser, the environment will be changed back to Test as it is the default.

### Screenshots

![image](https://github.com/user-attachments/assets/9fd2f8dc-a614-497e-ba02-8077335a37b0)

**Comment by jkbquabeck** [comment]
Integration:
Only organization page refresh issued got fixed, but page refresh should be fixed for my organisation page as well.
We are in the development environment. If I click on the refresh button of the web browser, the environment will be changed back to the test environment this issue not yet fixed.
