### ISSUE TITLE
Wrong percentages in Dashboard

### ISSUE THREAD

**Issue by tmberthold** [sovity/authority-portal#262]
### Description - What happened? *

The Dashboard shows the uptime of the DAPS, Data Catalogue and Logging House measured in percentages. The percentages apparently can shown values that are greater than 100%.

### Expected Behavior *

The uptime should be calculated correctly. An uptime greater than 100% can not be achieved.

### Observed Behavior *

526% and 148%

### Steps to Reproduce

- Navigate to "Dashboard" (then depends on whether the dashboard has those problems)

### Context Information

- Seen on: `Portal: 2.3.0`
- This bug can be observed on different environments in the same AP

Comment TB: None of the 6 dashboards I looked at showed such values, so I have to accept as reported that this is apparently somehow possible.

### Screenshots

![image](https://github.com/user-attachments/assets/b727286f-4d8a-45a0-a426-0ecfb307f893)

**Comment by jkbquabeck** [comment]
Can be verified in prod portal: https://portal.mobility-dataspace.eu/dashboard
