### ISSUE TITLE
No automatic forwarding to "Setup Connector" in Connector registration process

### ISSUE THREAD

**Issue by tmberthold** [sovity/authority-portal#274]
### Description - What happened? *

`The user should navigate to the setup connector page after clicking on the register connector button`

### Expected Behavior *

`After clicking on the register connector button user should navigate to setup connector page`

### Observed Behavior *

No automatic forwarding to "Setup Connector" page, user has to click it manually

### Steps to Reproduce

```
Log in to the MDS Portal.
Navigate to "My Connectors"
Click on add connector button
Select as I have connector option
Add valid connector details
Click on next button
Enter valid data and click on generate certificate page
Click on register connector button
```

**Comment by kamilczaja** [comment]
Already fixed
