### ISSUE TITLE
Forwarding after login to the originally requested URL

### ISSUE THREAD

**Issue by tmberthold** [sovity/authority-portal#280]
# Enhancement

## Description
If the user uses a direct link to any AP page and is not logged in, they will be redirected to the login screen, but after logging in they will remain on the respective main-page of the AP and will not be redirected to their original destination before logging in.

Original:
`If the person is not logged in, the log in mask shall be displayed and upon successful completion, the user shall be redirected to the data catalogue and not the main page of the Portal.`

**Comment by jkbquabeck** [comment]
Bug still occurs

**Comment by jkbquabeck** [comment]
Will open new issue as a bug ticket
