### ISSUE TITLE
Environments in URLs

### ISSUE THREAD

**Issue by tmberthold** [sovity/authority-portal#281]
### Description - What happened? *

`Hardcoded environment URL found in AuthPortal UI: [...]/catalog?environmentId=test`

### Expected Behavior *

`Hardcoded environment URL should be removed`

### Observed Behavior *

environment mentioned in URL

### Steps to Reproduce

```
Steps to reproduce the behavior:
- Log in to the MDS Portal.
- Navigate to "Data Catalogue page"
```

**Comment by AbdullahMuk** [comment]
Bug will not be resolved based on below context.

@tmberthold please communicate to MDS Project process accordingly. /cc @jkbquabeck 

Thank you for bringing this to our attention. I understand that there may be some confusion regarding the environment IDs in the URL. Let me clarify:
 
The environment IDs in the URL are not “hardcoded” as it might seem. They are dynamically generated and essential for the functionality of our system. This design decision was made based on the specific requirements of the MDS. Also, the AP v4.0.0 release does introduce the use of environment IDs in the URL.
 
The feature request required permalinks for each data offer, which necessitates the use of these environment IDs. Additionally, the feature request required wanted a unique link to the data catalog for each environment. This also requires the use of environment IDs.
 
This design choice was made with careful consideration and is crucial for the system to function as intended.
