### ISSUE TITLE
UX of UI: Alignment on Organizations page of Data Offer Types

### ISSUE THREAD

**Issue by tmberthold** [sovity/authority-portal#286]
# Enhancement

## Description
We have received feedback that the following UI part is visually confusing as UX and a better presentation is needed (e.g. guidelines).
It is best to involve a UI/UX designer here or agree on a solution beforehand.

![image](https://github.com/user-attachments/assets/4aaa5474-7123-4aed-84d8-e00c3e5c32cb)

```[tasklist]
- [ ] Fix the GitHub Projects Labels, Sprint and other Metadata
- [ ] Refine a Solution Proposal / Work Breakdown
```

**Comment by jkbquabeck** [comment]
@kamilczaja isn't  this already fixed?

**Comment by kamilczaja** [comment]
> @kamilczaja isn't this already fixed?

It's not, also needs design input. And probably a job for @illfixit

**Comment by illfixit** [comment]
I'll just show a few options



![Image](https://github.com/user-attachments/assets/26913188-6d35-42b9-84e5-31df42f83a32)



![Image](https://github.com/user-attachments/assets/8c6cc938-2da3-4533-93cf-34158f197b0b)




![Image](https://github.com/user-attachments/assets/bfaae0a3-37f2-419d-96a3-b59176af3e3e)

**Comment by tmberthold** [comment]
I asked the original feedback provider for the preferred solution. Accordingly waiting here on feedback.

**Comment by tmberthold** [comment]
> Update: First feedback is in. Voting runs until 12:00 CET tomorrow. If nothing special happens between now and then, we could then implement the by then chosen solution.

@illfixit we have a winner, it is this option (3.):

![image](https://github.com/user-attachments/assets/2b9894f9-7541-4fcb-96fd-339c9d25fa09)
