### ISSUE TITLE
Needs splitting: Multiple UI Gaps

### ISSUE THREAD

**Issue by jkbquabeck** [sovity/authority-portal#3]
# Enhancement

## Description

As a user of the authority portal I want to have a consistent UX in the Authority Portal.

## Stakeholders

@jkbquabeck 

## Solution Proposal and Work Breakdown

```[tasklist]
- [x] Highlight to users that this is the "MDS Portal"
- [x] When clicking on the MDS logo in the upper left, a link to "MDS News"/ "Home" should be activated
- [x] Do not show the role in the upper left corner (below the MDS logo)
- [x] When entering the one time code during login, show that this code can be found in the Authenticator (or similar)
- [x] On the last page of the registration process: Remove MDS News and MDS Blog Articles and link only to the MDS website.
- [x] Use fonts arial and arial bold
```

**Comment by illfixit** [comment]
Arial is already the default font-family

![Image](https://github.com/sovity/authority-portal/assets/66363651/bee31ee9-7b0e-41a9-a1ce-05818cf7dccb)

**Comment by illfixit** [comment]
"When clicking on the MDS logo in the upper left, a link to "MDS News"/ "Home" should be activated"

Also already opens a new tab with this link (Home):
https://mobility-dataspace.eu/de

**Comment by illfixit** [comment]
"On the last page of the registration process: Remove MDS News and MDS Blog Articles and link only to the MDS website."

We have 1. Mds Main Page 2. MDS Community 3. MDS Events
can delete the last two

**Comment by jkbquabeck** [comment]
> "When clicking on the MDS logo in the upper left, a link to "MDS News"/ "Home" should be activated"
> 
> Also already opens a new tab with this link (Home): https://mobility-dataspace.eu/de

This is not what is meant. Currently the logo link opens the MDS marketing page in a new tab. It should point to the authority portal page "MDS Home"

**Comment by illfixit** [comment]
> > "When clicking on the MDS logo in the upper left, a link to "MDS News"/ "Home" should be activated"
> > Also already opens a new tab with this link (Home): https://mobility-dataspace.eu/de
> 
> This is not what is meant. Currently the logo link opens the MDS marketing page in a new tab. It should point to the authority portal page "MDS Home"

as you wish but we don't have MDS News in AP
