### ISSUE TITLE
Operator user - delete and cancel confirmation popup window for the central components page frequently switches between the tabs

### ISSUE THREAD

**Issue by tmberthold** [sovity/authority-portal#304]
### Description - What happened? *

`In Central Components, when we click on the delete button in the confirmation popup window, the delete and cancel buttons frequently switch between the tabs`

### Expected Behavior *

Delete and cancel button should work properly

### Observed Behavior *

`In Central Components, when we click on the delete button in the confirmation popup window, the delete and cancel buttons frequently switch between the tabs`

### Steps to Reproduce

```
Steps to reproduce the behavior:
- Login to Auth Portal
- Navigate to central components page
- Click on delete button in conformation popup window frequently switching delete and cancel button
```

### Context Information

`Portal: [e.g. 4.1.0]`

### Screenshots

![image](https://github.com/user-attachments/assets/f6710dff-9095-4071-9940-b2cf59406c63)

**Comment by illfixit** [comment]
### Control Center >> Users & Roles >> User
![Image](https://github.com/user-attachments/assets/c1ddc59c-8036-4fb8-8b92-cc08961c979d)

### Control Center >> My Profile
![Image](https://github.com/user-attachments/assets/c08357d2-4478-4b9a-8833-e5436cc673d7)

### My Connectors >> Connector Details
![Image](https://github.com/user-attachments/assets/8f5033c8-16c2-477a-9b52-e214859bec49)

### All Connectors >> Connector Details
![Image](https://github.com/user-attachments/assets/b34d8a70-e86f-4445-b19d-3700c5807384)

### Central Components >> Central Component Details
![Image](https://github.com/user-attachments/assets/d8c9af8d-1ddb-427c-b264-2317a2e41cad)

### Provided Connectors >> Connector Details
![Image](https://github.com/user-attachments/assets/6a5e7452-3742-4377-88ed-0f22472a3fd9)
