### ISSUE TITLE
What logging house implementation can be used with the authority portal ?

### ISSUE THREAD

**Issue by xamcost** [sovity/authority-portal#333]
# Documentation Update Request

## Description

Hi there! First of all, thank you for your efforts in the data space community! My team has been using your [the community edition of your connector](https://github.com/sovity/edc-ce), and we are interested in trying the authority portal. In its documentation, it is specified that a running _logging house_ is needed. So here's my question: what logging house implementation can be used ? [This one](https://github.com/Fraunhofer-AISEC/ids-clearing-house-service) looks promising... but seems to rely on another connector implementation (Trusted connector).

## Current Documentation

https://github.com/sovity/authority-portal/blob/main/docs/deployment-guide/goals/production/README.md#dataspace

## Proposed Changes

Adding a list of links pointing to logging/clearing house implementations that can be used with the Sovity EDC CE and Authority portal.

**Comment by tmberthold** [comment]
Hello and thank you for the request and sorry for the late reply.
I'm personally not sure if a logging house actually needs to be deployed.
In any case, if one is available in the dataspace, the uptime status of the logging house can be tracked and displayed in the AP dashboard.

**Comment by xamcost** [comment]
Thank you for your answer. We will try setting up the authority portal without a logging house and see how it goes then.

**Comment by AbdullahMuk** [comment]
Thank you for raising this question. 

Separate to this issue, we will update our documentation to clarify that a Logging House is currently not a mandatory requirement to setup a functional AP (community edition).
