### ISSUE TITLE
UX Gap: Cancelling Invites, Users & Organizations

### ISSUE THREAD

**Issue by richardtreier** [sovity/authority-portal#6]
# Gap

## Note

Result from FE Task Refinement session. Might be a duplicate. Check for that

# Description

- Status Quo:
    - Flow 1: Invited Organization + User:
        - User Status: INVITED
        - Group Status: INVITED
        - Right now: No actions
        - [x] "Cancel" user should delete both (status CANCEL)            
        - [x] "Cancel" organization should delete both (status CANCEL)
    - Flow 2: Self-Registed Organization + User:
        - User Status: PENDING (?)
        - Group Status: CREATED (?)
        - [x] "Reject" user should cancel both
        - [x] "Reject" organization should cancel both
    - Flow 3: Org Admin invites another user. An admin should still be able reject / approve.
    - [x] Does rejecting an organization brick the user from ever trying again?
    - [ ] ~~When "shutting down" an organization, also pending invites will be removed.~~
- [x] Rejecting / Deleting Users should work regardless of state they or their organization is in

**Comment by kamilczaja** [comment]
After a short investigation, I'm pretty sure that everything works as intended now.
Closing as done.
