### ISSUE TITLE
"Up since ..." not showing

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#62]
### Description - What happened? *

- On the dashboard "Up since ..." does not show when hovering over the "Up" status.
Also I think we should place this hint more visibly in general, as it is not intuitive to hover over the UP status.

- The Dashboard displays the uptime of all components in percent. It is not apperant over which timespan this percentage is calculated. To my knowledge the calculation takes the last 30 days into account. Could you please add this information to the Dashboard?

- The Data Catalogue in the Dashboard is reffered to as "Broker". Could you please rename this to "Data Catalogue"?

### Expected Behavior *

/

### Observed Behavior *

/

**Comment by illfixit** [comment]
It looks like we have some type mismatch.

Response vom Server:
{
    "brokerStatus": {
        "componentStatus": "UP",
        "uptimePercentage": 100.0,
        "timeSpan": 2592000.000000000,
        "upSince": 191.704305614
    },
    "dapsStatus": {
        "componentStatus": "UP",
        "uptimePercentage": 100.0,
        "timeSpan": 2592000.000000000,
        "upSince": 191.698959614
    },
    "loggingHouseStatus": {
        "componentStatus": "DOWN",
        "uptimePercentage": 0.0,
        "timeSpan": 2592000.000000000,
        "upSince": 0.0
    },
    "onlineConnectors": 0,
    "disturbedConnectors": 0,
    "offlineConnectors": 0
}
 
but in FE based on the TS Library these 2 fields should be objects with properties like {seconds: ..., nano: ...} etc.
FE and Fake BE work accordingly and therefore with real BE the "up since" tooltip" (not a tooltip later) won't show the proper info.

    timeSpan: UptimeStatusDtoTimeSpan;
    upSince: UptimeStatusDtoUpSince;

**Comment by kamilczaja** [comment]
> It looks like we have some type mismatch.
> 
> Response vom Server: { "brokerStatus": { "componentStatus": "UP", "uptimePercentage": 100.0, "timeSpan": 2592000.000000000, "upSince": 191.704305614 }, "dapsStatus": { "componentStatus": "UP", "uptimePercentage": 100.0, "timeSpan": 2592000.000000000, "upSince": 191.698959614 }, "loggingHouseStatus": { "componentStatus": "DOWN", "uptimePercentage": 0.0, "timeSpan": 2592000.000000000, "upSince": 0.0 }, "onlineConnectors": 0, "disturbedConnectors": 0, "offlineConnectors": 0 }
> 
> but in FE based on the TS Library these 2 fields should be objects with properties like {seconds: ..., nano: ...} etc. FE and Fake BE work accordingly and therefore with real BE the "up since" tooltip" (not a tooltip later) won't show the proper info.
> 
> ```
> timeSpan: UptimeStatusDtoTimeSpan;
> upSince: UptimeStatusDtoUpSince;
> ```

Just to satisfy my curiosity... The API DTOs are generated from the BE's API definitions. I don't quite understand how the fake backend and the frontend could have implemented this differently than the Backend.

Could you elaborate further? @illfixit
