### ISSUE TITLE
No Data Privacy and Legal Notice Links at the Login page

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#79]
### Description - What happened? *

There is no link for Data Privacy and Legal Notice at the Login page of portal. These links are mandatory for every page of the portal

### Expected Behavior *

/

### Observed Behavior *

/

**Comment by kamilczaja** [comment]
To add some more context, the Keycloak login page is meant here, therefore the Keycloak MDS Theme needs to be adjusted
