### ISSUE TITLE
"Back to application" during logout redirects wrong

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#8]
### Description - What happened? *

When I log out as a logged-in user and click on "Back to application" I am redirected to the "landing page" suggesting a successful log-out, although I am still logged in (click on "Log in" to prove).

### Expected Behavior *

Instead, I should be redirected to the Dashboard.

### Observed Behavior *

see Description

**Comment by kamilczaja** [comment]
I did some investigating, so I'll share the context here.
When a user presses the "Log out" button and then does not confirm the logout but rather clicks on "Back to application", the user gets redirected to the Portal's unauthenticated portal page.
At this stage, the user is still logged in according to Keycloak and has a valid access token.

But:

The pings to `/user-info `return `401 Unauthorized` which hints at the backend revoking access on the first "Log out" button and thus not redirecting the user to the authenticated part of the FE.

This is further confirmed by setting the redirect URL to `PORTAL_FQDN/mds-home` and still seing the user getting stuck on the unauthenticated landing page.
