### ISSUE TITLE
Organization details sidebar shows wrong information

### ISSUE THREAD

**Issue by kamilczaja** [sovity/authority-portal#92]
### Description - What happened? *

When viewing the organization details on the sidebar, you can also view details of the organization members. When doing that and then clicking on the same organization in the overview again, the sidebar's title changes but the shown data is still that of the user

### Expected Behavior *

Sidebar should reload to show organization details

### Observed Behavior *

Sidebar shows user details instead of organization details

### Steps to Reproduce

1. Go to Authority Section -> Organizations
2. Click on an organization
3. In the sidebar, click on the user list icon
4. Click on a user
5. Click on the organization (in the list) again

### Context Information

https://github.com/sovity/authority-portal/assets/46053356/26b06fdd-ca3d-47cf-8af8-3b0acf40e96b

**Comment by illfixit** [comment]
works fine?

https://github.com/sovity/authority-portal/assets/66363651/63ba9a13-16ad-4d67-be07-6ee982204cf3
